Question 1: Module v/s Library

MODULE:  A module is a set of lines of code which are used for a specific purpose and can be used in other programs as it is.
         A module can be of three types:
             1) one created by the user (ie us)
             2) one created by someone else or one which is developed externally
             3) one which is pedefined (already present)
         Example: suppose i create a module (basically code a function) and save it in a python3 file named first_module.py

In [ ]:
def python_class_a2(student): # 1) one which is created by the user
  print("morning",  + student)

I can use the above module in another file(s) by using the import statement:

In [ ]:
import first_module     # 2) one which is created by someone else

first_module.greeting("naom chomsky")

In [1]:
import platform    # 3) importing a Built-in Modules

x = platform.system() 
print(x)                     
                             

Windows


LIBRARY: Python library is a collection of functions and methods that allows us to perform many actions without writing our code.  Numpy is an example of a  library used for numerical operations.

Question 2: How to make a matrix which has each of its elements as 2? (there is a by default module only for zeros and ones)

In [6]:
import numpy as np
x=np.ones((7,7))
y=x*2
y

array([[2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2.]])

Question 2: Suppose we have an array -- [0.26,0.34,0.49] how can this array be converted into  --[5.26,5.34,5.49]

In [14]:
x=np.random.rand(3)
x


array([0.59418127, 0.24875448, 0.74445643])

In [16]:
x

array([1.78254382, 0.74626345, 2.23336928])

In [17]:
z= [5,5,5]
z1=np.array(z)
z1

array([5, 5, 5])

In [21]:
x+z1

array([5.59418127, 5.24875448, 5.74445643])

Question 3: Explain functionality of the following:

1) TILE 
Syntax: numpy.tile(array_name, reps) where array_name is the name of the array already created on which tile is to be applied and reps is the number of timesit has to be repeated.
 
NOTE: If reps (repetitions) has length l, then the result will have dimension of max(l, array_name.ndim) ie max of length , array's dimensions

In [23]:
array_name = np.array([0, 1, 2])
np.tile(array_name, 2)

array([0, 1, 2, 0, 1, 2])

If array_name.ndim < l, arrray_name is promoted to be l-dimensional by prepending new axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication, or shape (1, 1, 3) for 3-D replication. If this is not the desired behavior, promote A to l-dimensions manually before calling this function.

If array_name.ndim > l, reps is promoted to array_name.ndim by pre-pending 1’s to it. Thus for an array_name of shape (2, 3, 4, 5), a reps of (2, 2) is treated as (1, 1, 2, 2).

Note : Although tile may be used for broadcasting

2) DIAG
Syntax: numpy.diag(a, k=0) 
It returns an array which has the diagonal of the asked matrix as an output
a : a is the array whose diagonal is to be found
If a is a 2-D array, return a copy of its k-th diagonal. If v is a 1-D array, return a 2-D array with v on the k-th diagonal.
k : k is an integer value which is optional
Diagonal in question. The default is 0. Use k>0 for diagonals above the main diagonal, and k<0 for diagonals below the main diagonal.

In [27]:
p =[12,34,45,98,67,31,40,92,6]
p1=np.array(p)
p1

array([12, 34, 45, 98, 67, 31, 40, 92,  6])

In [26]:
np.diag(p)

array([[12,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 34,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 45,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 98,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 67,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 31,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 40,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 92,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  6]])

In [34]:
z9=p1.reshape(3,3)
z9

array([[12, 34, 45],
       [98, 67, 31],
       [40, 92,  6]])

In [35]:
np.diag(z9)

array([12, 67,  6])

3) INVERSE
Syntax: numpy.linalg.inv(array_name)
Compute the (multiplicative) inverse of a matrix.

Given a square matrix a, it returns the matrix ainv satisfying dot(a, ainv) = dot(ainv, a) = eye(a.shape[0]).
I have to use numpy.linalg.inv() function to calculate the inverse of a matrix. The inverse of a matrix is such that if it is multiplied by the original matrix, it results in identity matrix.

In [44]:
q = np.array([[1,2],[3,4]]) 
r = np.linalg.inv(q) 
print(q)
print(r)
print(np.dot(q,r)) #gives product of two arrays

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


4) TRANSPOSE
Syntax: matrix_name.transpose(*axes)     ie.Returns a view of the array with axes transposed.

For a 1-D array, this has no effect. (To change between column and row vectors, first cast the 1-D array into a matrix object.) For a 2-D array, this is the usual matrix transpose. For an n-D array, if axes are given, their order indicates how the axes are permuted (see Examples). If axes are not provided and a.shape = (i[0], i[1], ... i[n-2], i[n-1]), then a.transpose().shape = (i[n-1], i[n-2], ... i[1], i[0]).

Parameters:	
axes : None, tuple of ints, or n ints
None or no argument: reverses the order of the axes.
tuple of ints: i in the j-th place in the tuple means a’s i-th axis becomes a.transpose()’s j-th axis.
n ints: same as an n-tuple of the same ints (this form is intended simply as a “convenience” alternative to the tuple form)

In [53]:
a = np.array([[1, 2], [3, 4]])
print(a)
np.transpose(a)

[[1 2]
 [3 4]]


array([[1, 3],
       [2, 4]])

Question 4: Stacking of arrays in Python : Horizontal and Vertical stacking
Stacking means to join a sequence of arrays along a new axis. It is of two types:
   1) Horizontal stacking:
   Stack arrays in sequence horizontally (column wise)
   Syntax: numpy.hstack(tup) where tup : sequence of ndarrays -The arrays must have the same shape along all but the second        axis, except 1-D arrays which can be any length.
    
   This is equivalent to concatenation along the second axis, except for 1-D arrays where it concatenates along the first axis.    This function makes most sense for arrays with up to 3 dimensions. For instance, for pixel-data with a height (first axis),    width (second axis), and r/g/b channels (third axis). The functions concatenate, stack and block provide more general          stacking and concatenation operations.

In [54]:
i= np.array((1,2,3))
i1 = np.array((2,3,4))
np.hstack((i,i1))

array([1, 2, 3, 2, 3, 4])

   2) Vertical stacking:
   Stack arrays in sequence vertically (row wise)
   Syntax: numpy.vstack(tup) where tup : sequence of ndarrays -The arrays must have the same shape along all but the      first    axis. 1-D arrays must have the same length. This is equivalent to concatenation along the first axis after 1-D arrays of        shape (N,) have been reshaped to (1,N). Rebuilds arrays divided by vsplit.

   This function makes most sense for arrays with up to 3 dimensions. For instance, for pixel-data with a height (first axis),    width (second axis), and r/g/b channels (third axis). The functions concatenate, stack and block provide more general          stacking and concatenation operations.

In [55]:
l= np.array([1, 2, 3])
m= np.array([2, 3, 4])
np.vstack((l,m))

array([[1, 2, 3],
       [2, 3, 4]])

In [56]:
a1 = np.array([[1, 2], 
              [3, 4]]) 
  
b1 = np.array([[5, 6], 
              [7, 8]]) 
# vertical stacking 
print("Vertical stacking:\n", np.vstack((a1, b1))) 
  
# horizontal stacking 
print("\nHorizontal stacking:\n", np.hstack((a1, b1))) 

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]
